spring:
  application:
    name: auth-gateway
  
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP

# 日志配置
logging:
  level:
    com.auth.center.gateway: debug
    org.springframework.cloud.gateway: debug