server:
  port: 8080

spring:
  application:
    name: auth-gateway
  
  cloud:
    nacos:
      username:
      password:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
  config:
    import:
      - optional:nacos:auth-gateway.yml
      - optional:nacos:common-redis.yml

# 日志配置
logging:
  level:
    com.auth.center.gateway: debug
    org.springframework.cloud.gateway: debug