spring:
  application:
    name: auth-server
  
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        shared-configs[0]:
          data-id: common-datasource.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[1]:
          data-id: common-redis.yml
          group: DEFAULT_GROUP
          refresh: true
        extension-configs[0]:
          data-id: auth-server.yml
          group: DEFAULT_GROUP
          refresh: true
  
  # 配置文件包含
  config:
    import:
      - classpath:application-auth.yml

# 日志配置
logging:
  level:
    com.auth.center.auth: debug
    org.springframework.security: debug