spring:
  application:
    name: message-service
  
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        shared-configs[0]:
          data-id: common-datasource.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[1]:
          data-id: common-redis.yml
          group: DEFAULT_GROUP
          refresh: true
    
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          output:
            producer:
              group: message-service-group

# RocketMQ配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: message-service-group