spring:
  application:
    name: user-service
  
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        shared-configs[0]:
          data-id: common-datasource.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[1]:
          data-id: common-redis.yml
          group: DEFAULT_GROUP
          refresh: true
          
  datasource:
    url: jdbc:mysql://localhost:3306/auth_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.auth.center.user.infrastructure.persistence.po