spring:
  application:
    name: monitor-service
  
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        shared-configs[0]:
          data-id: common-datasource.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[1]:
          data-id: common-redis.yml
          group: DEFAULT_GROUP
          refresh: true
  
  boot:
    admin:
      ui:
        title: 认证中心监控面板
      discovery:
        converter:
          management-url: management-url

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always